name: "build-all"

on:
  # Run on each commit to this repo.
  push:

  # Run every day at 2AM.
  schedule:
    - cron: '0 2 * * *'

  # Allow manual activations.
  workflow_dispatch:

permissions:
  # Allow release creation
  contents: write

env:
  APIO_REPO: 'FPGAwars/apio'

jobs:

  # ----- Parameters collection job

  prepare:

    runs-on: ubuntu-latest

    outputs:
      apio_config: ${{steps.get_apio_config_json.outputs.apio_config}}

    env:
      APIO_TAG: value-tbd
      APIO_COMMIT: value-tbd
      APIO_VERSION: value-tbd

    steps:

      - name: Checkout the apio repo
        uses: actions/checkout@v4
        with:
          repository: ${{env.APIO_REPO}}
          ref: develop
          path: apio-repo
          fetch-depth: 0


      - name: Pip install apio
        run: |
          python -m pip install --upgrade pip
          pip install -e apio-repo



      - name: Get apio config JSON
        id: get_apio_config_json
        run: |
          apio_commit=$(git -C apio-repo rev-parse HEAD)
          echo "${apio_commit}"

          apio_version="$(pip show apio | grep Version: | cut -d ' ' -f2)"
          echo ${apio_version}

          apio_tag="$(date +'%Y-%m-%d')"
          echo "${apio_tag}"

          apio_config=$(jq -n -c \
              --arg APIO_REPO    "$APIO_REPO" \
              --arg APIO_COMMIT  "$apio_commit" \
              --arg APIO_VERSION "$apio_version" \
              --arg APIO_TAG     "$apio_tag" \
              '{APIO_REPO: $APIO_REPO, APIO_COMMIT: $APIO_COMMIT, APIO_VERSION: $APIO_VERSION, APIO_TAG: $APIO_TAG}')

          echo "$apio_config"
          echo "apio_config=$apio_config" >> "$GITHUB_OUTPUT"



  # ----- Children build jobs

  build-darwin_arm64:
    needs: prepare
    uses: ./.github/workflows/build-darwin-arm64.yml
    with:
      apio_config: ${{needs.prepare.outputs.apio_config}}
    secrets: inherit


  build-linux-x86-64:
    needs: prepare
    uses: ./.github/workflows/build-linux-x86-64.yml
    with:
      apio_config: ${{needs.prepare.outputs.apio_config}}
    secrets: inherit


  build-windows-amd64:
    needs: prepare
    uses: ./.github/workflows/build-windows-amd64.yml
    with:
      apio_config: ${{needs.prepare.outputs.apio_config}}
    secrets: inherit


  # ----- Release creation job

  publish:
      needs: [prepare, build-darwin_arm64, build-linux-x86-64, build-windows-amd64]

      runs-on: ubuntu-latest

      env:
        APIO_TAG: value-tbd
        APIO_COMMIT: value-tbd
        APIO_VERSION: value-tbd

      steps:


        # This copy the apio config json key/val to the env.
        - name: Set up env
          run: |
            echo '${{needs.prepare.outputs.apio_config}}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV


        - name: Download the build artifacts
          uses: actions/download-artifact@v4
          with:
            path: artifacts


        - name: List artifact files
          run: |
            find artifacts


        - name: Create GitHub release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{env.APIO_TAG}}
            name: ${{env.APIO_TAG}}
            body: |
              This is an automated daily build of the Apio's repo `develop` branch.

              <br>

              | Build var     | Value                      |
              | :------------ | :------------------------- |
              | APIO_REPO     | ${{env.APIO_REPO}}         |
              | APIO_TAG      | ${{env.APIO_TAG}}          |
              | APIO_VERSION  | ${{env.APIO_VERSION}}      |
              | APIO_COMMIT   | ${{env.APIO_COMMIT}}       |

              <br>
              
              Additional resources:
              * [installation instructions](https://github.com/${{github.repository}}).
              * [Official Apio releases](https://github.com/FPGAwars/apio/releases).
              * [Last commit](https://github.com/${{env.APIO_REPO}}/commit/${{env.APIO_COMMIT}})

            files: |
              # Darwin
              artifacts/apio-darwin-arm64-bundle/**
              artifacts/apio-darwin-arm64-installer/**

              # Linux
              artifacts/apio-linux-x86-64-bundle/**
              artifacts/apio-linux-x86-64-debian/**

              # Windows
              artifacts/apio-windows-amd64-bundle/**
              artifacts/apio-windows-amd64-installer/**

