name: build-linux-x86-64


on:
  workflow_call:
    inputs:
      apio_config:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash  # Set Bash as the default shell

    steps:
      - name: Check architecture
        run: |
          uname
          uname -m
          if [[ "$(uname)" != "Linux" || "$(uname -m)" != "x86_64" ]]; then
            exit 1
          fi


      # This copies the apio config json key/val to the env.
      - name: Set up env
        run: |
          echo '${{inputs.apio_config}}' | jq .
          echo '${{inputs.apio_config}}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV


      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Adjust version as needed


      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: builder-repo


      - name: Checkout the apio repo
        uses: actions/checkout@v4
        with:
          repository: ${{env.APIO_REPO}}
          ref: ${{env.APIO_COMMIT}}
          path: apio-repo
          fetch-depth: 0

      - name: Pip install apio
        run: |
          python -m pip install --upgrade pip
          pip install -e apio-repo


      - name: Pip install pyinstaller
        run: |
          pip install pyinstaller


      # A temporary workaround until this fix will be released
      # https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/913
      # We delete the usb line in the hook pyinstaller hook list file
      # rthooks.dat to disable this hook.
      - name: Patch pyinstaller usb hook
        run: |
          module_dir=$(dirname "$(python -c 'import _pyinstaller_hooks_contrib; print(_pyinstaller_hooks_contrib.__file__)')")
          f="$module_dir/rthooks.dat"
          cat -n $f
          sed -i.bak "/'usb':/d" "$f" && rm -f "${f}.bak"
          cat -n $f


      - name: Set up working directories
        run: |
          mkdir _work
          mkdir _dist
          pwd
          ls -la .


      - name: Run pyinstaller
        run: |
          pyinstaller \
            --log-level=DEBUG \
            --workpath _work \
            --distpath _dist \
            builder-repo/.github/workflows/resources/apio-pyinstaller.spec
          echo "_dist:"
          ls -al _dist
          echo "_dist/apio:"
          ls -al _dist/apio

      - name: Check for symlinks
        run: |
          # If _dist/_internal contains symlinks, we need to revisit how
          # we copy it around, while preserving symlinks. May need to copy
          # using rsync, or just move it around instead of copying.
          if find _dist -type l | grep -q .; then
              echo "PyInstaller files contain symlinks"
              exit 1
          else
              echo "No symlinks"
          fi


      - name: Download the build-info artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{env.APIO_WF}}
          run_id: ${{env.APIO_RUN}}
          name: apio-build-info-${{env.APIO_RUN}}
          path: artifacts


      - name: Add the BUILD-INFO file
        run: |
          cp artifacts/BUILD-INFO _dist/apio
          cat -n _dist/apio/BUILD-INFO


      - name: Add the LICENSE file
        run: |
          cp apio-repo/LICENSE _dist/apio
          cat _dist/apio/LICENSE

      - name: List the bundle files
        run: |
          find _dist


      - name: Zip the pyinstaller bundle
        run: |
          pushd _dist
          bundle="apio-linux-x86-64-${APIO_VERSION}-${APIO_TAG}-bundle.zip"
          zip -r -y ../${bundle} apio
          popd
          ls -al


      - name: Populate the debian package
        run: |
          mkdir _debian

          # -- /opt/apio
          mkdir -p _debian/opt/apio
          cp _dist/apio/apio _debian/opt/apio
          cp -r _dist/apio/_internal _debian/opt/apio

          # /usr/local/bin
          mkdir -p _debian/usr/local/bin
          pushd _debian/usr/local/bin
          ln -s ../../../opt/apio/apio apio
          popd

          # Package control file
          mkdir _debian/DEBIAN
          control="_debian/DEBIAN/control"
          sed "s/\[APIO_VERSION\]/${APIO_VERSION}/g" builder-repo/.github/workflows/resources/linux/control.template > ${control}

          # Show info
          find _debian
          cat -n ${control}

      - name: Set permissions for debian control file
        run: find _debian/DEBIAN -type f -exec chmod 644 {} \;

      - name: Build .deb package
        run: |
          dpkg-deb --build --root-owner-group _debian "apio-linux-x86-64-${APIO_VERSION}-${APIO_TAG}-debian.deb"
          ls -l


      - name: Export the pyinstaller archive as an artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "apio-linux-x86-64-bundle"
          path: "apio-linux-x86-64-${{env.APIO_VERSION}}-${{env.APIO_TAG}}-bundle.zip"


      - name: Export the installer file as an artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "apio-linux-x86-64-debian"
          path: "apio-linux-x86-64-${{env.APIO_VERSION}}-${{env.APIO_TAG}}-debian.deb"

