name: "build-all"

on:
  # Run on each commit to this repo.
  push:

  # Run every day at 2AM.
  schedule:
    - cron: '0 2 * * *'

  # Allow manual activations.
  workflow_dispatch:

permissions:
  # Allow release creation
  contents: write

env:
  APIO_REPO: 'FPGAwars/apio'

jobs:

  # ----- Parameters collection job

  prepare:

    runs-on: ubuntu-latest

    outputs:
      apio_config: ${{steps.get_apio_config_json.outputs.apio_config}}
      # apio_build_info: "apio_build_info"

    # env:
    #   APIO_TAG: value-tbd
    #   APIO_COMMIT: value-tbd
    #   APIO_VERSION: value-tbd

    steps:

      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: builder-repo


      - name: Checkout the apio repo
        uses: actions/checkout@v4
        with:
          repository: ${{env.APIO_REPO}}
          ref: develop
          path: apio-repo
          fetch-depth: 0


      - name: Pip install apio
        run: |
          python -m pip install --upgrade pip
          pip install -e apio-repo


      - name: Get apio config JSON
        id: get_apio_config_json
        run: |
          apio_commit=$(git -C apio-repo rev-parse HEAD)
          echo "${apio_commit}"

          apio_version="$(pip show apio | grep Version: | cut -d ' ' -f2)"
          echo ${apio_version}

          apio_tag="$(date +'%Y-%m-%d')"
          echo "${apio_tag}"

          apio_config=$(jq -n -c \
              --arg APIO_WF      "${{ github.workflow }}" \
              --arg APIO_RUN     "${{github.run_id}}" \
              --arg APIO_REPO    "$APIO_REPO" \
              --arg APIO_COMMIT  "$apio_commit" \
              --arg APIO_VERSION "$apio_version" \
              --arg APIO_TAG     "$apio_tag" \
              '{APIO_WF: $APIO_WF, APIO_RUN: $APIO_RUN, APIO_REPO: $APIO_REPO, APIO_COMMIT: $APIO_COMMIT, APIO_VERSION: $APIO_VERSION, APIO_TAG: $APIO_TAG}')

          echo "$apio_config"
          echo "apio_config=$apio_config" >> "$GITHUB_OUTPUT"


      # This copies the apio config json key/val to the env.
      - name: Set up env
        run: |
          echo '${{steps.get_apio_config_json.outputs.apio_config}}' | jq .
          echo '${{steps.get_apio_config_json.outputs.apio_config}}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV


      - name: Create build info file
        run: |
          builder_commit=$(git -C builder-repo rev-parse HEAD)

          echo "${apio_commit}"
          out="BUILD_INFO"

          echo "Builder info" >  ${out}
          echo "Time:             $(date +'%Y-%m-%d %H:%M:%S %Z')" >> ${out}
          echo "Build repo:       ${{github.repository}}" >> ${out}
          echo "Builder commit:   $builder_commit" >>  ${out}
          echo "Run ID:           ${{github.run_id}}" >> ${out}
          echo "Run number:       ${{github.run_number}}" >> ${out}

          echo >> ${out}
          echo "Apio info" >>  ${out}
          echo "Apio repo:        $APIO_REPO" >> ${out}
          echo "Apio SHA:         $APIO_COMMIT" >>  ${out}
          echo "Apio version:     $APIO_VERSION" >> ${out}
          echo "Release tag:      $APIO_TAG" >> ${out}

          ls -al
          cat -n BUILD_INFO

      # Because we export it also to independent builder workflow, we need
      # a unique name in case multiple instances of this workflows run
      # at the same time.
      - name: Export apio build info artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "apio-build-info-${{github.run_id}}"
          path: "BUILD_INFO"


  # ----- Children build jobs

  build-darwin-arm64:
    needs: prepare
    uses: ./.github/workflows/build-darwin-arm64.yml
    with:
      apio_config: ${{needs.prepare.outputs.apio_config}}
    secrets: inherit


  build-linux-x86-64:
    needs: prepare
    uses: ./.github/workflows/build-linux-x86-64.yml
    with:
      apio_config: ${{needs.prepare.outputs.apio_config}}
    secrets: inherit


  build-windows-amd64:
    needs: prepare
    uses: ./.github/workflows/build-windows-amd64.yml
    with:
      apio_config: ${{needs.prepare.outputs.apio_config}}
    secrets: inherit


  # ----- Release creation job

  publish:
      needs: [prepare, build-darwin-arm64, build-linux-x86-64, build-windows-amd64]

      runs-on: ubuntu-latest

      env:
        APIO_TAG: value-tbd
        APIO_COMMIT: value-tbd
        APIO_VERSION: value-tbd

      steps:


        # This copy the apio config json key/val to the env.
        - name: Set up env
          run: |
            echo '${{needs.prepare.outputs.apio_config}}' | jq .
            echo '${{needs.prepare.outputs.apio_config}}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV


        - name: Download the build artifacts
          uses: actions/download-artifact@v4
          with:
            path: artifacts


        - name: List artifact files
          run: |
            find artifacts

            # Remove the run id unique part.
            mv artifacts/apio-build-info-${APIO_RUN} artifacts/apio-build-info

            echo
            find artifacts
            cat artifacts/apio-build-info/BUILD_INFO


        - name: Prepare release text
          run: |

            echo '${{needs.prepare.outputs.apio_config}}' | jq . > APIO_CONFIG.json

            out=RELEASE_BODY.txt
            echo "This is an automated daily build of the Apio's repo 'develop' branch." >> $out

            echo -e "\n<br>\n" >> $out

            echo '```' >> $out
            echo "APIO_CONFIG" >> $out
            cat APIO_CONFIG.json >> $out
            echo '```' >> $out

            echo -e "\n<br>\n" >> $out

            echo '```' >> $out
            cat artifacts/apio-build-info/BUILD_INFO >> $out
            echo '```' >> $out

            echo -e "\n<br>\n" >> $out

            echo 'Additional resources:' >> $out
            echo '  * [installation instructions](https://github.com/${{github.repository}}).' >> $out
            echo '  * [Official Apio releases](https://github.com/FPGAwars/apio/releases).' >> $out
            echo '  * [Last commit](https://github.com/${{env.APIO_REPO}}/commit/${{env.APIO_COMMIT}})' >> $out

            cat -n $out



        - name: Create GitHub release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{env.APIO_TAG}}
            name: ${{env.APIO_TAG}}
            body_path: RELEASE_BODY.txt
            files: |
              # Darwin
              artifacts/apio-darwin-arm64-bundle/**
              artifacts/apio-darwin-arm64-installer/**

              # Linux
              artifacts/apio-linux-x86-64-bundle/**
              artifacts/apio-linux-x86-64-debian/**

              # Windows
              artifacts/apio-windows-amd64-bundle/**
              artifacts/apio-windows-amd64-installer/**

